export const nptelAllWeeksAnswers = [
  {
    key: "week-1",
    title: "Week 1 - Assignment answers",
    answers: [
      {
        id: 1,
        option: 3,
        answer: "Statistics, Computer Science, and Domain Expertise",
      },
      {
        id: 2,
        option: 2,
        answer:
          "It includes data like text, speech, and video that doesn’t fit into traditional tables",
      },
      { id: 3, option: [1, 2, 3], answer: ["Pandas", "NumPy", "TensorFlow"] },
      {
        id: 4,
        option: 3,
        answer:
          "Data scientists typically focus on post-analysis interpretation, while machine learning engineers focus on deployment and maintenance",
      },
      { id: 5, option: 2, answer: "Knowledge Representation" },
      {
        id: 6,
        option: [1, 3, 4],
        answer: [
          "Problem Solving",
          "Communication and Perception",
          "Decision Making",
        ],
      },
      { id: 7, option: 2, answer: "Guido van Rossum" },
      {
        id: 8,
        option: [1, 2, 4],
        answer: ["Object-Oriented", "Open Source", "Portable"],
      },
      { id: 9, option: 2, answer: "Colab" },
      { id: 10, option: 1, answer: "Jupyter" },
      {
        id: 11,
        option: [1, 3],
        answer: [
          "Pre-installed data science libraries",
          "Integration with Kaggle datasets",
        ],
      },
      { id: 12, option: 3, answer: "Google Drive" },
      { id: 13, option: 3, answer: "Outcome (0 or 1)" },
      { id: 14, option: 4, answer: "Median House Value" },
      {
        id: 15,
        option: 2,
        answer: "Open the .ipynb file and click 'Open in Colab'",
      },
    ],
  },
  {
    key: "week-2",
    title: "Week 2 - Assignment answers",
    answers: [
      { id: 1, option: 1, answer: "Descriptive and Inferential Statistics" },
      { id: 2, option: [1, 3, 4], answer: ["Mean", "Median", "Mode"] },
      { id: 3, option: 2, answer: "Interquartile Range (IQR)" },
      { id: 4, option: 3, answer: "Cluster Sampling" },
      {
        id: 5,
        option: [1, 2, 3, 4],
        answer: ["T-test", "Z-test", "Chi-square Test", "ANOVA"],
      },
      { id: 6, option: 2, answer: "Statistical significance" },
      { id: 7, option: 2, answer: "Two-sample t-test" },
      { id: 8, option: 3, answer: "P(A|B)" },
      { id: 9, option: 2, answer: "Multiplication Rule" },
      {
        id: 10,
        option: [1, 2, 3, 4],
        answer: [
          "Probability of Impossible Event is 0",
          "Probability of Certain Event is 1",
          "Addition Rule",
          "Multiplication Rule",
        ],
      },
      { id: 11, option: 1, answer: "N - 1" },
      { id: 12, option: 3, answer: "Qualitative Nominal" },
      { id: 13, option: 2, answer: "Frequency Plot" },
      { id: 14, option: 2, answer: "Testing for no specific direction" },
      {
        id: 15,
        option: [1, 2, 3, 4],
        answer: ["Minimum", "Maximum", "Median", "Quartiles"],
      },
    ],
  },
  {
    key: "week-3",
    title: "Week 3 - Assignment answers",
    answers: [
      { id: 1, option: 1, answer: "Integer, Float" },
      { id: 2, option: 3, answer: "input()" },
      { id: 3, option: 2, answer: "String" },
      { id: 4, option: 2, answer: "+" },
      { id: 5, option: 4, answer: "for" },
      { id: 6, option: 1, answer: "Continue" },
      { id: 7, option: 3, answer: "do-while loop(conceptually)" },
      { id: 8, option: 2, answer: "for variable in sequence:" },
      { id: 9, option: 2, answer: "while loop" },
      { id: 10, option: 2, answer: "and" },
      {
        id: 11,
        option: [1, 2, 3],
        answer: ["and, ", "or, ", "not"],
      },
      { id: 12, option: 3, answer: "Acts as a placeholder" },
      { id: 13, option: 2, answer: "**" },
      { id: 14, option: 3, answer: "3" },
      { id: 15, option: 3, answer: "def" },
    ],
  },
  {
    key: "week-4",
    title: "Week 4 - Assignment answers",
    answers: [
      { id: 1, option: 4, answer: "Dictionary" },
      { id: 2, option: 2, answer: "dict()" },
      { id: 3, option: 3, answer: "keys()" },
      { id: 4, option: 2, answer: "update()" },
      { id: 5, option: 3, answer: "Keys must be immutable" },
      { id: 6, option: 3, answer: "Set" },
      { id: 7, option: 2, answer: "set()" },
      { id: 8, option: 2, answer: "&" },
      { id: 9, option: 3, answer: "casefold()" },
      { id: 10, option: 2, answer: "len()" },
      { id: 11, option: 4, answer: "Tuple" },
      { id: 12, option: 3, answer: "()" },
      { id: 13, option: 2, answer: "+" },
      { id: 14, option: 2, answer: "append()" },
      { id: 15, option: 3, answer: "Difference" },
    ],
  },
  {
    key: "week-5",
    title: "Week 5 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "Compilation" },
      { id: 2, option: 2, answer: "__init__" },
      { id: 3, option: 4, answer: "(SuperclassName)" },
      { id: 4, option: 1, answer: "__str__" },
      { id: 5, option: 3, answer: "TypeError" },
      { id: 6, option: 3, answer: "finally" },
      { id: 7, option: 2, answer: "w" },
      { id: 8, option: 2, answer: "writelines()" },
      { id: 9, option: 3, answer: "file.closed" },
      { id: 10, option: 2, answer: "readline()" },
      { id: 11, option: 2, answer: "seek()" },
      {
        id: 12,
        option: 3,
        answer: "It can contain both functions and classes",
      },
      { id: 13, option: 2, answer: "__init__.py" },
      { id: 14, option: 2, answer: "Easier maintenance" },
      { id: 15, option: 2, answer: "import" },
    ],
  },
  {
    key: "week-6",
    title: "Week 6 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "NumPy" },
      { id: 2, option: 2, answer: "randint()" },
      { id: 3, option: 2, answer: "shuffle()" },
      {
        id: 4,
        option: 2,
        answer: "Perform operations on arrays with different shapes",
      },
      { id: 5, option: 1, answer: "ndim" },
      { id: 6, option: 3, answer: "zeros()" },
      { id: 7, option: 3, answer: "float64" },
      { id: 8, option: 2, answer: "mean()" },
      { id: 9, option: 3, answer: "Default numerical index" },
      { id: 10, option: 2, answer: "read_csv()" },
      { id: 11, option: 4, answer: "to_string()" },
      { id: 12, option: 2, answer: "str.split()" },
      { id: 13, option: 3, answer: "describe()" },
      { id: 14, option: 3, answer: "groupby()" },
      { id: 15, option: 1, answer: "head()" },
    ],
  },
  {
    key: "week-7",
    title: "Week 7 - Assignment answers",
    answers: [
      { id: 1, option: 1, answer: "to_csv()" },
      { id: 2, option: 3, answer: "inner" },
      { id: 3, option: 3, answer: "Left Join" },
      { id: 4, option: 1, answer: "merge(..., how='outer')" },
      { id: 5, option: 4, answer: "Seaborn" },
      { id: 6, option: 2, answer: "kdeplot()" },
      { id: 7, option: 3, answer: "pairplot" },
      { id: 8, option: 3, answer: "heatmap" },
      { id: 9, option: 1, answer: "hist()" },
      { id: 10, option: 2, answer: "box plot" },
      { id: 11, option: 3, answer: "Scikit-learn" },
      { id: 12, option: 1, answer: "model_selection" },
      { id: 13, option: 2, answer: "KNeighborsClassifier" },
      { id: 14, option: 2, answer: "Dimensionality Reduction" },
      { id: 15, option: 2, answer: "MinMaxScaler" },
    ],
  },
];
