export const nptelAllWeeksAnswers = [
  {
    key: "week-1",
    title: "Week 1 - Assignment answers",
    answers: [
      {
        id: 1,
        option: 3,
        answer: "Statistics, Computer Science, and Domain Expertise",
      },
      {
        id: 2,
        option: 2,
        answer:
          "It includes data like text, speech, and video that doesn’t fit into traditional tables",
      },
      { id: 3, option: [1, 2, 3], answer: ["Pandas", "NumPy", "TensorFlow"] },
      {
        id: 4,
        option: 3,
        answer:
          "Data scientists typically focus on post-analysis interpretation, while machine learning engineers focus on deployment and maintenance",
      },
      { id: 5, option: 2, answer: "Knowledge Representation" },
      {
        id: 6,
        option: [1, 3, 4],
        answer: [
          "Problem Solving",
          "Communication and Perception",
          "Decision Making",
        ],
      },
      { id: 7, option: 2, answer: "Guido van Rossum" },
      {
        id: 8,
        option: [1, 2, 4],
        answer: ["Object-Oriented", "Open Source", "Portable"],
      },
      { id: 9, option: 2, answer: "Colab" },
      { id: 10, option: 1, answer: "Jupyter" },
      {
        id: 11,
        option: [1, 3],
        answer: [
          "Pre-installed data science libraries",
          "Integration with Kaggle datasets",
        ],
      },
      { id: 12, option: 3, answer: "Google Drive" },
      { id: 13, option: 3, answer: "Outcome (0 or 1)" },
      { id: 14, option: 4, answer: "Median House Value" },
      {
        id: 15,
        option: 2,
        answer: "Open the .ipynb file and click 'Open in Colab'",
      },
    ],
  },
  {
    key: "week-2",
    title: "Week 2 - Assignment answers",
    answers: [
      { id: 1, option: 1, answer: "Descriptive and Inferential Statistics" },
      { id: 2, option: [1, 3, 4], answer: ["Mean", "Median", "Mode"] },
      { id: 3, option: 2, answer: "Interquartile Range (IQR)" },
      { id: 4, option: 3, answer: "Cluster Sampling" },
      {
        id: 5,
        option: [1, 2, 3, 4],
        answer: ["T-test", "Z-test", "Chi-square Test", "ANOVA"],
      },
      { id: 6, option: 2, answer: "Statistical significance" },
      { id: 7, option: 2, answer: "Two-sample t-test" },
      { id: 8, option: 3, answer: "P(A|B)" },
      { id: 9, option: 2, answer: "Multiplication Rule" },
      {
        id: 10,
        option: [1, 2, 3, 4],
        answer: [
          "Probability of Impossible Event is 0",
          "Probability of Certain Event is 1",
          "Addition Rule",
          "Multiplication Rule",
        ],
      },
      { id: 11, option: 1, answer: "N - 1" },
      { id: 12, option: 3, answer: "Qualitative Nominal" },
      { id: 13, option: 2, answer: "Frequency Plot" },
      { id: 14, option: 2, answer: "Testing for no specific direction" },
      {
        id: 15,
        option: [1, 2, 3, 4],
        answer: ["Minimum", "Maximum", "Median", "Quartiles"],
      },
    ],
  },
  {
    key: "week-3",
    title: "Week 3 - Assignment answers",
    answers: [
      { id: 1, option: 1, answer: "Integer, Float" },
      { id: 2, option: 3, answer: "input()" },
      { id: 3, option: 2, answer: "String" },
      { id: 4, option: 2, answer: "+" },
      { id: 5, option: 4, answer: "for" },
      { id: 6, option: 1, answer: "Continue" },
      { id: 7, option: 3, answer: "do-while loop(conceptually)" },
      { id: 8, option: 2, answer: "for variable in sequence:" },
      { id: 9, option: 2, answer: "while loop" },
      { id: 10, option: 2, answer: "and" },
      {
        id: 11,
        option: [1, 2, 3],
        answer: ["and, ", "or, ", "not"],
      },
      { id: 12, option: 3, answer: "Acts as a placeholder" },
      { id: 13, option: 2, answer: "**" },
      { id: 14, option: 3, answer: "3" },
      { id: 15, option: 3, answer: "def" },
    ],
  },
  {
    key: "week-4",
    title: "Week 4 - Assignment answers",
    answers: [
      { id: 1, option: 4, answer: "Dictionary" },
      { id: 2, option: 2, answer: "dict()" },
      { id: 3, option: 3, answer: "keys()" },
      { id: 4, option: 2, answer: "update()" },
      { id: 5, option: 3, answer: "Keys must be immutable" },
      { id: 6, option: 3, answer: "Set" },
      { id: 7, option: 2, answer: "set()" },
      { id: 8, option: 2, answer: "&" },
      { id: 9, option: 3, answer: "casefold()" },
      { id: 10, option: 2, answer: "len()" },
      { id: 11, option: 4, answer: "Tuple" },
      { id: 12, option: 3, answer: "()" },
      { id: 13, option: 2, answer: "+" },
      { id: 14, option: 2, answer: "append()" },
      { id: 15, option: 3, answer: "Difference" },
    ],
  },
  {
    key: "week-5",
    title: "Week 5 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "Compilation" },
      { id: 2, option: 2, answer: "__init__" },
      { id: 3, option: 4, answer: "(SuperclassName)" },
      { id: 4, option: 1, answer: "__str__" },
      { id: 5, option: 3, answer: "TypeError" },
      { id: 6, option: 3, answer: "finally" },
      { id: 7, option: 2, answer: "w" },
      { id: 8, option: 2, answer: "writelines()" },
      { id: 9, option: 3, answer: "file.closed" },
      { id: 10, option: 2, answer: "readline()" },
      { id: 11, option: 2, answer: "seek()" },
      {
        id: 12,
        option: 3,
        answer: "It can contain both functions and classes",
      },
      { id: 13, option: 2, answer: "__init__.py" },
      { id: 14, option: 2, answer: "Easier maintenance" },
      { id: 15, option: 2, answer: "import" },
    ],
  },
  {
    key: "week-6",
    title: "Week 6 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "NumPy" },
      { id: 2, option: 2, answer: "randint()" },
      { id: 3, option: 2, answer: "shuffle()" },
      {
        id: 4,
        option: 2,
        answer: "Perform operations on arrays with different shapes",
      },
      { id: 5, option: 1, answer: "ndim" },
      { id: 6, option: 3, answer: "zeros()" },
      { id: 7, option: 3, answer: "float64" },
      { id: 8, option: 2, answer: "mean()" },
      { id: 9, option: 3, answer: "Default numerical index" },
      { id: 10, option: 2, answer: "read_csv()" },
      { id: 11, option: 4, answer: "to_string()" },
      { id: 12, option: 2, answer: "str.split()" },
      { id: 13, option: 3, answer: "describe()" },
      { id: 14, option: 3, answer: "groupby()" },
      { id: 15, option: 1, answer: "head()" },
    ],
  },
  {
    key: "week-7",
    title: "Week 7 - Assignment answers",
    answers: [
      { id: 1, option: 1, answer: "to_csv()" },
      { id: 2, option: 3, answer: "inner" },
      { id: 3, option: 3, answer: "Left Join" },
      { id: 4, option: 1, answer: "merge(..., how='outer')" },
      { id: 5, option: 4, answer: "Seaborn" },
      { id: 6, option: 2, answer: "kdeplot()" },
      { id: 7, option: 3, answer: "pairplot" },
      { id: 8, option: 3, answer: "heatmap" },
      { id: 9, option: 1, answer: "hist()" },
      { id: 10, option: 2, answer: "box plot" },
      { id: 11, option: 3, answer: "Scikit-learn" },
      { id: 12, option: 1, answer: "model_selection" },
      { id: 13, option: 2, answer: "KNeighborsClassifier" },
      { id: 14, option: 2, answer: "Dimensionality Reduction" },
      { id: 15, option: 2, answer: "MinMaxScaler" },
    ],
  },
  {
    key: "week-8",
    title: "Week 8 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "fillna(median)" },
      { id: 2, option: 4, answer: "MinMaxScaler" },
      {
        id: 3,
        option: 3,
        answer: "Create synthetic samples for minority class",
      },
      { id: 4, option: 2, answer: "Mean = 0 and Standard deviation = 1" },
      { id: 5, option: 3, answer: "0 to 1" },
      { id: 6, option: 1, answer: "train_test_split" },
      { id: 7, option: 3, answer: "Image generation" },
      {
        id: 8,
        option: 3,
        answer: "Convert categorical data into binary vectors",
      },
      { id: 9, option: 3, answer: "KBinsDiscretizer" },
      { id: 10, option: 3, answer: "F1 Score" },
      { id: 11, option: 2, answer: "Inputs" },
      {
        id: 12,
        option: [1, 2, 4],
        answer: [
          "Drop the attribute, ",
          "Fill with mean/median, ",
          "Drop the corresponding record",
        ],
      },
      {
        id: 13,
        option: [1, 2, 3],
        answer: [
          "Makes the attributes lie in the same range, ",
          "Prevents domination of large-valued features, ",
          "Improves model interpretability",
        ],
      },
      {
        id: 14,
        option: [1, 2, 3],
        answer: ["Normalization, ", "Standardization, ", "Min-max scaling"],
      },
      {
        id: 15,
        option: [1, 3, 4],
        answer: [
          "Supervised learning algorithms, ",
          "Cross-validation techniques, ",
          "Dimensionality reduction",
        ],
      },
    ],
  },
  {
    key: "week-9",
    title: "Week 9 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "Majority of k nearest neighbors" },
      { id: 2, option: 2, answer: "Euclidean distance" },
      { id: 3, option: 2, answer: "Better classification ability" },
      { id: 4, option: 3, answer: "Entropy" },
      { id: 5, option: 3, answer: "(TP + TN) / (Total)" },
      { id: 6, option: 3, answer: "Mean Squared Error" },
      {
        id: 7,
        option: 2,
        answer: "Proportion of variance explained by the model",
      },
      { id: 8, option: 2, answer: "No convergence" },
      { id: 9, option: 2, answer: "Data shows a nonlinear relationship" },
      { id: 10, option: 2, answer: "Actual positive predicted as positive" },
      { id: 11, option: [1, 2], answer: ["Regression, ", "Classification"] },
      {
        id: 12,
        option: [1, 2, 3],
        answer: ["Entropy, ", "Information Gain, ", "Gini Index"],
      },
      {
        id: 13,
        option: [1, 2, 3],
        answer: [
          "Value of k, ",
          "Distance metric used, ",
          "Size of the training set",
        ],
      },
      {
        id: 14,
        option: [1, 2, 3],
        answer: [
          "Mean Absolute Error (MAE), ",
          "Mean Squared Error (MSE), ",
          "Root Mean Squared Error (RMSE)",
        ],
      },
      {
        id: 15,
        option: [1, 2, 3, 4],
        answer: [
          "True Positive, ",
          "False Positive, ",
          "False Negative, ",
          "True Negative",
        ],
      },
    ],
  },
  {
    key: "week-10",
    title: "Week 10 - Assignment answers",
    answers: [
      { id: 1, option: 2, answer: "A cluster" },
      { id: 2, option: 3, answer: "Classification" },
      { id: 3, option: 1, answer: "Number of clusters" },
      { id: 4, option: 3, answer: "Single linkage" },
      { id: 5, option: 2, answer: "Algorithm overshoots minimum" },
      {
        id: 6,
        option: 3,
        answer: "Good performance on training but poor on testing",
      },
      {
        id: 7,
        option: 2,
        answer: "Reduce model complexity and prevent overfitting",
      },
      { id: 8, option: 2, answer: "Sigmoid" },
      { id: 9, option: 1, answer: "Binary classification" },
      { id: 10, option: [2, 3], answer: ["Sigmoid, ", "Tanh"] },
      {
        id: 11,
        option: [1, 2, 3],
        answer: [
          "Clustering, ",
          "Association Rule Mining, ",
          "Anomaly Detection",
        ],
      },
      {
        id: 12,
        option: [1, 2, 3],
        answer: [
          "Learning Rate, ",
          "Number of Hidden Layers, ",
          "Maximum Iterations",
        ],
      },
      {
        id: 13,
        option: [1, 2, 4],
        answer: ["L1 Regularization, ", "L2 Regularization, ", "Dropout"],
      },
      {
        id: 14,
        option: [1, 2, 3],
        answer: ["Single linkage, ", "Complete linkage, ", "Centroid"],
      },
      {
        id: 15,
        option: [1, 2, 4],
        answer: [
          "Neither underfitting nor overfitting ,",
          "Good performance on validation set ,",
          "Generalizing well to unseen data",
        ],
      },
    ],
  },
  {
    key: "week-11",
    title: "Week 11 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "Backpropagation" },
      { id: 2, option: 2, answer: "TensorFlow" },
      { id: 3, option: 3, answer: "Feature/Independent variable" },
      { id: 4, option: 2, answer: "Image and video processing" },
      { id: 5, option: 2, answer: "Pooling layer" },
      { id: 6, option: 2, answer: "Bag of Words" },
      { id: 7, option: 2, answer: "Sequential data" },
      { id: 8, option: 2, answer: "Tokenization" },
      { id: 9, option: 2, answer: "Automatically learn spatial hierarchies" },
      { id: 10, option: 2, answer: "Map words into numerical vectors" },
      {
        id: 11,
        option: [1, 2, 3],
        answer: [
          "Computer Vision, ",
          "Speech Recognition, ",
          "Natural Language Processing",
        ],
      },
      {
        id: 12,
        option: [1, 2, 3],
        answer: ["Convolutional Layer, ", "Pooling Layer, ", "Flatten Layer"],
      },
      {
        id: 13,
        option: [1, 2, 3, 4],
        answer: [
          "One-to-one, ",
          "One-to-many, ",
          "Many-to-one, ",
          "Many-to-many",
        ],
      },
      {
        id: 14,
        option: [1, 2, 3, 4],
        answer: [
          "Data requirements, ",
          "Need for Feature Engineering, ",
          "Interpretability, ",
          "Model complexity",
        ],
      },
      {
        id: 15,
        option: [1, 2, 3],
        answer: ["Tokenization, ", "Padding, ", "Vectorization"],
      },
    ],
  },
  {
    key: "week-12",
    title: "Week 12 - Assignment answers",
    answers: [
      { id: 1, option: 3, answer: "Regression" },
      { id: 2, option: 3, answer: "Root Mean Squared Error" },
      { id: 3, option: 3, answer: "80%–20%" },
      { id: 4, option: 3, answer: "train_test_split()" },
      { id: 5, option: 3, answer: "0 to 1" },
      { id: 6, option: 1, answer: "StandardScaler" },
      { id: 7, option: 4, answer: "Actual negative predicted as negative" },
      {
        id: 8,
        option: 2,
        answer:
          "Considers total true positives, false positives, and false negatives",
      },
      { id: 9, option: 3, answer: "accuracy_score" },
      { id: 10, option: 3, answer: "Gradient Boosting" },
      {
        id: 11,
        option: [1, 2, 3],
        answer: [
          "Kaggle, ",
          "AWS datasets, ",
          "UCI Machine Learning Repository",
        ],
      },
      {
        id: 12,
        option: [1, 2, 3],
        answer: ["Data loading, ", "Data visualization, ", "Model fine-tuning"],
      },
      {
        id: 13,
        option: [1, 2, 3],
        answer: [
          "Supervised learning, ",
          "Unsupervised learning, ",
          "Dimensionality reduction",
        ],
      },
      {
        id: 14,
        option: [1, 2],
        answer: ["dropna(), ", "fillna()"],
      },
      {
        id: 15,
        option: [1, 2],
        answer: ["Features, ", "Response"],
      },
    ],
  },
];
